package release

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"time"
)

// RenderCatalog emits the Go source for catalog_gen.go.
//
// It emits LITERALS rather than an embedded JSON string parsed at startup. A
// generated file that can fail to parse at runtime would put a panic path into
// every shipped binary for no benefit; literals move the whole question to
// compile time.
//
// Output is deterministic — maps are emitted in sorted key order — so the
// drift gate compares bytes rather than meaning.
func RenderCatalog(c Catalog) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprint(&b, `// Code generated by novarel catalog; DO NOT EDIT.
//
// Regenerate with:  make catalog
// Verify with:      make catalog-check
//
// This is the compiled-in release catalog (P2-M7.3, D-M7.3-2c). T1.22 forbids
// a binary from fetching release metadata, so what a build claims about itself
// has to be linked in. It is generated from the checked-in intent, and the
// intent digest below is the join between a running binary and the decision a
// reviewer approved.

package catalog

import "time"

var compiled = Catalog{
`)
	fmt.Fprintf(&b, "\tVersion:      %q,\n", c.Version)
	fmt.Fprintf(&b, "\tIntentDigest: %q,\n", c.IntentDigest)
	fmt.Fprintf(&b, "\tTargetSchema: %d,\n", c.TargetSchema)
	fmt.Fprintf(&b, "\tPlatforms:    %s,\n", goStrings(c.Platforms))
	fmt.Fprintf(&b, "\tSupportEpoch: %s,\n", goTime(c.SupportEpoch))
	fmt.Fprintf(&b, "\tSupportUntil: %s,\n", goTime(c.SupportUntil))

	fmt.Fprint(&b, "\tSupportedPredecessors: []Predecessor{\n")
	for _, p := range c.SupportedPredecessors {
		fmt.Fprint(&b, "\t\t{\n")
		fmt.Fprintf(&b, "\t\t\tKind: %q,\n", p.Kind)
		if p.Commit != "" {
			fmt.Fprintf(&b, "\t\t\tCommit: %q,\n", p.Commit)
		}
		if p.Version != "" {
			fmt.Fprintf(&b, "\t\t\tVersion: %q,\n", p.Version)
		}
		fmt.Fprintf(&b, "\t\t\tSchema: %d,\n", p.Schema)
		fmt.Fprintf(&b, "\t\t\tSupportEpoch: %s,\n", goTime(p.SupportEpoch))
		fmt.Fprint(&b, "\t\t},\n")
	}
	fmt.Fprint(&b, "\t},\n")

	fmt.Fprint(&b, "\tRepositories: map[string]string{\n")
	for _, k := range sortedKeys(c.Repositories) {
		fmt.Fprintf(&b, "\t\t%q: %q,\n", k, c.Repositories[k])
	}
	fmt.Fprint(&b, "\t},\n")

	fmt.Fprint(&b, "\tProfiles: CapabilityProfiles{\n")
	fmt.Fprintf(&b, "\t\tCore: %s,\n", goStrings(c.Profiles.Core))
	if len(c.Profiles.Roles) > 0 {
		fmt.Fprint(&b, "\t\tRoles: map[string][]string{\n")
		for _, k := range sortedKeys(c.Profiles.Roles) {
			fmt.Fprintf(&b, "\t\t\t%q: %s,\n", k, goStrings(c.Profiles.Roles[k]))
		}
		fmt.Fprint(&b, "\t\t},\n")
	}
	fmt.Fprint(&b, "\t},\n")

	fmt.Fprint(&b, "}\n")

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("catalog: generated source does not parse: %w\n%s", err, b.String())
	}
	return out, nil
}

func goStrings(v []string) string {
	if len(v) == 0 {
		return "nil"
	}
	var b bytes.Buffer
	b.WriteString("[]string{")
	for i, s := range v {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", s)
	}
	b.WriteString("}")
	return b.String()
}

func goTime(t time.Time) string {
	if t.IsZero() {
		return "time.Time{}"
	}
	u := t.UTC()
	return fmt.Sprintf("time.Date(%d, time.%s, %d, %d, %d, %d, %d, time.UTC)",
		u.Year(), u.Month(), u.Day(), u.Hour(), u.Minute(), u.Second(), u.Nanosecond())
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
