// Code generated by novarel catalog; DO NOT EDIT.
//
// Regenerate with:  make catalog
// Verify with:      make catalog-check
//
// This is the compiled-in release catalog (P2-M7.3, D-M7.3-2c). T1.22 forbids
// a binary from fetching release metadata, so what a build claims about itself
// has to be linked in. It is generated from the checked-in intent, and the
// intent digest below is the join between a running binary and the decision a
// reviewer approved.

package catalog

import "time"

var compiled = Catalog{
	Version:      "v0.3.0",
	IntentDigest: "sha256:6fa1df3eece8b37f582c761b09ea30a9386df56153bdf8739cf0000f350d15e4",
	TargetSchema: 19,
	Platforms:    []string{"linux/amd64"},
	SupportEpoch: time.Date(2026, time.August, 11, 0, 0, 0, 0, time.UTC),
	SupportUntil: time.Date(2027, time.February, 11, 0, 0, 0, 0, time.UTC),
	SupportedPredecessors: []Predecessor{
		{
			Kind:         "commit",
			Commit:       "143c459",
			Schema:       18,
			SupportEpoch: time.Date(2026, time.August, 8, 0, 0, 0, 0, time.UTC),
		},
	},
	Repositories: map[string]string{
		"nova-admin":       "ghcr.io/nova-archive/nova-admin",
		"nova-coordinator": "ghcr.io/nova-archive/nova-coordinator",
		"nova-node":        "ghcr.io/nova-archive/nova-node",
	},
	Profiles: CapabilityProfiles{
		Core: []string{"pin-change-log/v1", "snapshot/v1"},
		Roles: map[string][]string{
			"assignment-destination": []string{"blob-transfer/v1"},
			"possession-audit":       []string{"audit-block-hash/v1"},
			"read-source":            []string{"read-source/v1", "blob-transfer/v1"},
			"repair-source":          []string{"repair-stream/v1"},
		},
	},
}
